# Generated by Django 2.2.1 on 2019-06-06 12:39

from django.db import migrations
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
    ]
