# Generated by Django 2.2.2 on 2019-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_mealitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(default='Planned', max_length=15, verbose_name='Type'),
        ),
    ]
