# Generated by Django 2.2.1 on 2019-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userapilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_can_create_users',
            field=models.BooleanField(default=False),
        ),
    ]
