# Generated by Django 2.2.1 on 2019-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_user_can_create_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='workout_plan',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
